### PR TITLE
Explicitly set provisioner to bash

### PR DESCRIPTION
**Pull request by dci-aloughran**

### CODE REVIEW

**Comment by gchamon** [comment]
Any particular problem you are addressing with this pull request? The script already sets the shell as being bash using shebang

**Comment by dci-aloughran** [comment]
In the context of executing via AzureDevOps (I know, miles out of scope of this script) - it appears to execute each line of the bash script as an independent shell - therefore completely undermining the env variables and context for each line.

I submitted this (and am testing it off my branch) as a means of seeing if setting the interpreter like this would persist the env across the full set of files.  I'll get back to you if it works.

**Comment by dci-aloughran** [comment]
This hasn't helped - investigatting on the DevOPs side...

**Comment by gchamon** [comment]
@dci-aloughran let me know if I can help you. I don't use AzureDevOps though

**Comment by dci-aloughran** [comment]
Thanks for your help.

It appears to be a quirk with local-exec; I'm looking into it, but pain in the arse.

Really impressed with your project - looking forward to contributing back.

Regards,

Andy

**Comment by gchamon** [comment]
@dci-aloughran thanks! All the really hard work was done in https://github.com/upsidetravel/bucket-antivirus-function, I am just wrapping it for easy deployment in terraform

**Comment by gchamon** [comment]
regarding `local-exec`, I haven't had issues with that in particular, but with `file` and `remote-exec` provisioners. It really bothers me that such basic provisioners in terraform are not exactly what we would call reliable. If there is some workaround or improvement I could do to `local-exec` I will be glad to implement

**Pull request closed without merging**
